"""create tables for Branch and BankAccounts

Revision ID: 0b8b112cd007
Revises: 1996e9dd78e2
Create Date: 2024-12-18 13:34:27.401722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8b112cd007'
down_revision: Union[str, None] = '1996e9dd78e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
